name: Make 2.0.0-beta.27 branch
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    name: make le branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create branch from commit
      run: |
        git checkout -b v2-beta27-but-branch 0554d64fa67e77183a15dcf03145e00f717da631
      
    - name: Push branch to remote
      run: |
        git push origin v2-beta27-but-branch
